import type { Metadata } from "next";

import "./globals.css";
import { Box } from "@mui/material";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import { CheckedUsersProvider } from "@/context/CheckedUsersContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      
        <CheckedUsersProvider>
          <Box display="flex" flexDirection="column" height="100vh">
            <Box display="flex" flex="1" flexDirection="row-reverse">
              <Box width={240} flexShrink={0}>
                <Sidebar />
              </Box>
              <Box component="main" flex="1" p={2} overflow="hidden">
                {children}
              </Box>
            </Box>
            <Footer />
          </Box>
        </CheckedUsersProvider>
      </body>
    </html>
  );
}


