import type { Metadata } from "next";

import "./globals.css";
import { Box } from "@mui/material";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Box display="flex" flexDirection="column" height="100vh">
          <Box display="flex" flex="1">
            <Sidebar />
            <Box component="main" flex="1" p={2}>
              {children}
            </Box>
          </Box>
          <Footer />
        </Box>
      </body>
    </html>
  );
}


